import html
from pathlib import Path
from .config import JELLYFIN_URL
from .az_bar import az_bar
from .nav_switch import nav_switch
def write_page(
    outfile: Path,
    title: str,
    active_tab: str,
    lis_html: str,
    extra_bar_html: str = "",
    page_class: str = "",
    default_grid_px: int = 230,
):
    tabs = nav_switch(active_tab)
    body_class = " ".join([c for c in [page_class, active_tab] if c]).strip()
    is_dashboard = active_tab == "dashboard"
    is_films = active_tab == "films"
    az_buttons = "" if is_dashboard else az_bar()
    if is_films:
        sort_select_html = (
            "<select id='sortBy'>"
            "<option value='name' selected>Name</option>"
            "<option value='added'>Added</option>"
            "</select>"
        )
    else:
        sort_select_html = (
            "<select id='sortBy'>"
            "<option value='name' selected>Name</option>"
            "<option value='count'>Count</option>"
            "</select>"
        )
    grid_slider_html = ""
    if not is_dashboard:
        grid_slider_html = (
            "<div class='gridCtl' title='Grid size'>"
            "  <span class='gridLabel'>Grid</span>"
            f"  <input id='gridSize' type='range' min='160' max='420' step='10' value='{default_grid_px}' aria-label='Grid size'>"
            f"  <span class='gridVal' id='gridVal'>{default_grid_px}px</span>"
            "</div>"
        )
    qa_bar_html = ""
    active_filters_html = ""
    if is_films:
        qa_bar_html = (
            "<div class='qabar' id='qabar'>"
            "<button class='qa active' data-missing='ALL' type='button'>All</button>"
            "<button class='qa' data-missing='NOPEOPLE' type='button'>Missing models</button>"
            "<button class='qa' data-missing='NOSTUDIO' type='button'>Missing studios</button>"
            "<button class='qa' data-missing='NOGENRE' type='button'>Missing genres</button>"
            "<button class='qa' data-missing='UNWATCHED' type='button'>Unwatched</button>"
            "</div>"
        )
        active_filters_html = "<div class='activeFilters' id='activeFilters' style='display:none'></div>"
    jf_home_html = (
        f"<a class='jfHomeBtn' href='{JELLYFIN_URL}/web/index.html' target='_blank' rel='noopener' "
        "title='Open Jellyfin' aria-label='Open Jellyfin'>"
        "<img class='jfHomeIcon' "
        "src='jellyfinicon.png' "
        "alt='Jellyfin'>"
        "</a>"
    )
    if is_dashboard:
        topbar_inner_html = (
            "<div class='topinner'>"
            + jf_home_html
            + tabs +
            "<button class='refreshBtn' id='refreshBtn' type='button' title='Fetch new data'>↻</button>"
            "<div class='sort'>"
            "<button class='dashAddTop' id='dashAddTop' type='button' title='Add card'>+</button>"
            "<button class='dashBtn' id='dashReset' type='button' title='Reset layout'>X</button>"
            "</div>"
            "</div>"
        )
    else:
        topbar_inner_html = (
            "<div class='topinner'>"
            + jf_home_html
            + tabs +
            "<button class='refreshBtn' id='refreshBtn' type='button' title='Fetch new data'>↻</button>"
            "<input id='q' placeholder='Search...'>"
            "<div class='sort'>"
            "<div class='selectWrap'>"
            + sort_select_html +
            "</div>"
            "<button id='sortDir' title='Toggle sort order' type='button'>▲</button>"
            + grid_slider_html +
            "<span class='chip' id='shown'></span>"
            "</div>"
            "</div>"
        )
    outfile.write_text(
        "<!doctype html>"
        "<html lang='en'>"
        "<head>"
        "<meta charset='utf-8'>"
        "<meta name='viewport' content='width=device-width, initial-scale=1'>"
        f"<title>{html.escape(title)}</title>"
        "<link rel='stylesheet' href='styles.css'>"
        "</head>"
        f"<body class='{html.escape(body_class)}'>"
        "<div class='overlay' id='overlay' aria-hidden='true'>"
        "  <div class='overlayBox' id='overlayBox'>"
        "    <div class='overlayTitle'>Updating…</div>"
        "    <div class='overlayRule'></div>"
        "    <div class='overlaySteps'>"
        "      <div class='overlayStep' data-step='films'>"
        "        <span class='stepLabel'>Films</span>"
        "        <span class='stepIcon' aria-hidden='true'><span class='stepSpinner'></span></span>"
        "      </div>"
        "      <div class='overlayStep' data-step='models'>"
        "        <span class='stepLabel'>Models</span>"
        "        <span class='stepIcon' aria-hidden='true'><span class='stepSpinner'></span></span>"
        "      </div>"
        "      <div class='overlayStep' data-step='studios'>"
        "        <span class='stepLabel'>Studios</span>"
        "        <span class='stepIcon' aria-hidden='true'><span class='stepSpinner'></span></span>"
        "      </div>"
        "      <div class='overlayStep' data-step='genres'>"
        "        <span class='stepLabel'>Genres</span>"
        "        <span class='stepIcon' aria-hidden='true'><span class='stepSpinner'></span></span>"
        "      </div>"
        "    </div>"
        "    <div class='overlayRule'></div>"
        "    <div class='overlaySub'>Fetching new data from Jellyfin</div>"
        "  </div>"
        "</div>"
        "<div class='topbar'>"
        + topbar_inner_html +
        "</div>"
        + az_buttons +
        qa_bar_html +
        active_filters_html +
        extra_bar_html +
        "<div class='wrap'>"
        "<ul class='grid' id='list'>" + lis_html + "</ul>"
        "</div>"
        "<script>"
        "const q=document.getElementById('q');"
        "const list=document.getElementById('list');"
        "const shown=document.getElementById('shown');"
        "const azButtons=document.querySelectorAll('.az');"
        "const sortBy=document.getElementById('sortBy');"
        "const sortDirBtn=document.getElementById('sortDir');"
        "const refreshBtn=document.getElementById('refreshBtn');"
        "const overlay=document.getElementById('overlay');"
        "const overlayBox=document.getElementById('overlayBox');"
        "const tagButtons=document.querySelectorAll('.tag');"
        "const tagClear=document.getElementById('tagClear');"
        "const gridSize=document.getElementById('gridSize');"
        "const gridVal=document.getElementById('gridVal');"
        "const qaButtons=document.querySelectorAll('.qa');"
        "const activeFilters=document.getElementById('activeFilters');"
        "let activeLetter='ALL';"
        "let sortDir='asc';"
        "let selectedTags=new Set();"
        "let missingMode='ALL';"
        "const isFilmPage = document.body.classList.contains('films');"
        "if (isFilmPage && sortBy) {"
        "  sortBy.value = 'added';"
        "  sortDir = 'desc';"
        "  if (sortDirBtn) sortDirBtn.textContent = '▼';"
        "}"
        "const urlParams=new URLSearchParams(window.location.search);"
        "function parseCsvParam(key){"
        " const raw = (urlParams.get(key)||'').trim();"
        " if(!raw) return new Set();"
        " const parts = raw.split(',').map(x=>x.toLowerCase().trim()).filter(Boolean);"
        " return new Set(parts);"
        "}"
        "const legacyPerson=(urlParams.get('person')||'').toLowerCase().trim();"
        "const urlModels=parseCsvParam('model');"
        "if(legacyPerson && urlModels.size===0){ urlModels.add(legacyPerson); }"
        "const urlStudios=parseCsvParam('studio');"
        "const urlGenres=parseCsvParam('genre');"
        "let activeModels = urlModels;"
        "let activeStudios = urlStudios;"
        "let activeGenres = urlGenres;"
        "const initialMissing = (urlParams.get('missing')||'').toUpperCase().trim();"
        "if(isFilmPage && initialMissing){"
        "  const allowed = new Set(['ALL','NOPEOPLE','NOSTUDIO','NOGENRE','UNWATCHED']);"
        "  if(allowed.has(initialMissing)){"
        "    missingMode = initialMissing;"
        "    qaButtons.forEach(b=>{"
        "      const mm = (b.dataset.missing||'ALL');"
        "      b.classList.toggle('active', mm === missingMode);"
        "    });"
        "  }"
        "}"
        "function setGridSize(px){"
        " const v = Math.max(120, Math.min(600, parseInt(px,10) || 230));"
        " document.documentElement.style.setProperty('--cardMin', v + 'px');"
        " if(gridVal) gridVal.textContent = v + 'px';"
        " if(gridSize) gridSize.value = String(v);"
        " try{ localStorage.setItem('gridSizePx', String(v)); }catch(e){}"
        "}"
        "if(gridSize){"
        " const forced = isFilmPage ? 360 : 230;"
        " setGridSize(forced);"
        " gridSize.addEventListener('input', (e)=>{ setGridSize(e.target.value); });"
        "}"
        "function applySort(items){"
        " if(!sortBy) return;"
        " const key=sortBy.value;"
        " items.sort((a,b)=>{"
        "  let va,vb;"
        "  if(key==='count'){"
        "    va=parseInt(a.dataset.count||'0',10);"
        "    vb=parseInt(b.dataset.count||'0',10);"
        "  } else if(key==='added'){"
        "    va=parseInt(a.dataset.added||'0',10);"
        "    vb=parseInt(b.dataset.added||'0',10);"
        "  } else {"
        "    va=a.dataset.name||'';"
        "    vb=b.dataset.name||'';"
        "  }"
        "  if(va<vb) return sortDir==='asc'?-1:1;"
        "  if(va>vb) return sortDir==='asc'?1:-1;"
        "  return 0;"
        " });"
        "}"
        "function tagsMatch(li){"
        " if(selectedTags.size===0) return true;"
        " const tags = li.dataset.tags || '';"
        " for(const t of selectedTags){"
        "   if(!tags.includes('|' + t + '|')) return false;"
        " }"
        " return true;"
        "}"
        "function allInPipe(liValue, setVals){"
        " if(!setVals || setVals.size===0) return true;"
        " const s = liValue || '';"
        " for(const v of setVals){"
        "  if(!s.includes('|' + v + '|')) return false;"
        " }"
        " return true;"
        "}"
        "function modelsMatch(li){ return allInPipe(li.dataset.people || '', activeModels); }"
        "function studiosMatch(li){ return allInPipe(li.dataset.studios || '', activeStudios); }"
        "function genresMatch(li){ return allInPipe(li.dataset.genres || '', activeGenres); }"
        "function missingMatch(li){"
        " if(!isFilmPage) return true;"
        " if(missingMode==='ALL') return true;"
        " const hp = (li.dataset.haspeople||'0')==='1';"
        " const hs = (li.dataset.hasstudios||'0')==='1';"
        " const hg = (li.dataset.hasgenres||'0')==='1';"
        " const played = (li.dataset.played||'0')==='1';"
        " if(missingMode==='NOPEOPLE') return !hp;"
        " if(missingMode==='NOSTUDIO') return !hs;"
        " if(missingMode==='NOGENRE') return !hg;"
        " if(missingMode==='UNWATCHED') return !played;"
        " return true;"
        "}"
        "function syncMiniBadges(tag){"
        " document.querySelectorAll(`.tagMini[data-tag=\\\"${tag}\\\"]`).forEach(b=>{"
        "  b.classList.toggle('active', selectedTags.has(tag));"
        " });"
        "}"
        "function setToCsv(setVals){"
        " if(!setVals || setVals.size===0) return '';"
        " return Array.from(setVals).join(',');"
        "}"
        "function updateUrlParams(){"
        " try{"
        "  const u = new URL(window.location.href);"
        "  u.searchParams.delete('person');"
        "  const m = setToCsv(activeModels);"
        "  const s = setToCsv(activeStudios);"
        "  const g = setToCsv(activeGenres);"
        "  if(m) u.searchParams.set('model', m); else u.searchParams.delete('model');"
        "  if(s) u.searchParams.set('studio', s); else u.searchParams.delete('studio');"
        "  if(g) u.searchParams.set('genre', g); else u.searchParams.delete('genre');"
        "  history.replaceState(null, '', u.toString());"
        " }catch(e){}"
        "}"
        "function escHtml(s){"
        "  return String(s||'')"
        "    .replaceAll('&','&amp;')"
        "    .replaceAll('<','&lt;')"
        "    .replaceAll('>','&gt;')"
        "    .replaceAll('\"','&quot;')"
        "    .replaceAll(\"'\",'&#39;');"
        "}"
        "function titleCase(s){"
        " return String(s||'')"
        "  .split(' ')"
        "  .filter(Boolean)"
        "  .map(w => w ? (w[0].toUpperCase() + w.slice(1)) : '')"
        "  .join(' ');"
        "}"
        "function renderActiveFilters(){"
        " if(!isFilmPage || !activeFilters) return;"
        " const hasAny = (activeModels.size>0) || (activeStudios.size>0) || (activeGenres.size>0);"
        " if(!hasAny){"
        "  activeFilters.style.display='none';"
        "  activeFilters.innerHTML='';"
        "  return;"
        " }"
        " activeFilters.style.display='flex';"
        " const parts=[];"
        " parts.push(\"<span class='afLabel'>Filter:</span>\");"
        " function renderGroup(kind, setVals){"
        "  if(!setVals || setVals.size===0) return '';"
        "  const pills=[];"
        "  for(const v of Array.from(setVals)){"
        "   pills.push(\"<button type='button' class='afItem' data-remove-kind='\" + escHtml(kind) + \"' data-remove-val='\" + escHtml(v) + \"'>\" + titleCase(escHtml(v)) + \" <span class='afX' aria-hidden='true'>×</span></button>\");"
        "  }"
        "  return \"<span class='afGroup' data-kind='\" + escHtml(kind) + \"'>\" + pills.join(' ') + \"</span>\";"
        " }"
        " const groups=[];"
        " const gm = renderGroup('model', activeModels); if(gm) groups.push(gm);"
        " const gs = renderGroup('studio', activeStudios); if(gs) groups.push(gs);"
        " const gg = renderGroup('genre', activeGenres); if(gg) groups.push(gg);"
        " for(let i=0;i<groups.length;i++){"
        "  if(i>0) parts.push(\"<span class='afSep'>|</span>\");"
        "  parts.push(groups[i]);"
        " }"
        " parts.push(\"<span class='afSep'>|</span>\");"
        " parts.push(\"<button type='button' class='afClear' data-clear='1'>Clear</button>\");"
        " activeFilters.innerHTML = parts.join(' ');"
        "}"
        "function syncFilterChips(){"
        " document.querySelectorAll('.filterChip').forEach(ch=>{"
        "  const k=(ch.dataset.kind||'').toLowerCase();"
        "  const v=(ch.dataset.value||'').toLowerCase().trim();"
        "  const on ="
        "    (k==='model' && activeModels.has(v)) ||"
        "    (k==='studio' && activeStudios.has(v)) ||"
        "    (k==='genre' && activeGenres.has(v));"
        "  ch.classList.toggle('active', on);"
        " });"
        "}"
        "document.addEventListener('click', (e)=>{"
        " if(!isFilmPage) return;"
        " const rm = e.target.closest('.afItem');"
        " if(rm && activeFilters && activeFilters.contains(rm)){"
        "  e.preventDefault();"
        "  e.stopPropagation();"
        "  const kind = (rm.dataset.removeKind||'').toLowerCase();"
        "  const val = (rm.dataset.removeVal||'').toLowerCase().trim();"
        "  if(kind==='model') activeModels.delete(val);"
        "  if(kind==='studio') activeStudios.delete(val);"
        "  if(kind==='genre') activeGenres.delete(val);"
        "  updateUrlParams();"
        "  update();"
        "  return;"
        " }"
        " const clr = e.target.closest('.afClear');"
        " if(clr && activeFilters && activeFilters.contains(clr)){"
        "  e.preventDefault();"
        "  e.stopPropagation();"
        "  activeModels = new Set();"
        "  activeStudios = new Set();"
        "  activeGenres = new Set();"
        "  updateUrlParams();"
        "  update();"
        "  return;"
        " }"
        " const chip = e.target.closest('.filterChip');"
        " if(!chip) return;"
        " e.preventDefault();"
        " e.stopPropagation();"
        " const kind = (chip.dataset.kind||'').toLowerCase();"
        " const val = (chip.dataset.value||'').toLowerCase().trim();"
        " if(!kind || !val) return;"
        " if(kind==='model'){"
        "  if(activeModels.has(val)) activeModels.delete(val); else activeModels.add(val);"
        " } else if(kind==='studio'){"
        "  if(activeStudios.has(val)) activeStudios.delete(val); else activeStudios.add(val);"
        " } else if(kind==='genre'){"
        "  if(activeGenres.has(val)) activeGenres.delete(val); else activeGenres.add(val);"
        " }"
        " updateUrlParams();"
        " update();"
        "});"
        "function update(){"
        " const text=(q && q.value) ? q.value.toLowerCase().trim() : '';"
        " let visible=0;"
        " const items=Array.from(list.children);"
        " for(const li of items){"
        "  const name=li.dataset.display || li.textContent.trim();"
        "  const lower=name.toLowerCase();"
        "  const matchText=!text || lower.includes(text);"
        "  const matchLetter=(activeLetter==='ALL') || name.toUpperCase().startsWith(activeLetter);"
        "  const matchTags=tagsMatch(li);"
        "  const matchModels=modelsMatch(li);"
        "  const matchStudios=studiosMatch(li);"
        "  const matchGenres=genresMatch(li);"
        "  const matchMissing=missingMatch(li);"
        "  const ok=matchText && matchLetter && matchTags && matchModels && matchStudios && matchGenres && matchMissing;"
        "  li.style.display=ok?'':'none';"
        "  if(ok) visible++;"
        " }"
        " applySort(items);"
        " items.forEach(li=>list.appendChild(li));"
        " if(shown) shown.textContent = `${visible} shown`;"
        " if(isFilmPage){ syncFilterChips(); renderActiveFilters(); }"
        "}"
        "function resetOverlaySteps(){"
        " if(!overlayBox) return;"
        " overlayBox.innerHTML = "
        "  \"<div class='overlayTitle'>Updating…</div>\" +"
        "  \"<div class='overlayRule'></div>\" +"
        "  \"<div class='overlaySteps'>\" +"
        "    \"<div class='overlayStep' data-step='films'><span class='stepLabel'>Films</span><span class='stepIcon' aria-hidden='true'><span class='stepSpinner'></span></span></div>\" +"
        "    \"<div class='overlayStep' data-step='models'><span class='stepLabel'>Models</span><span class='stepIcon' aria-hidden='true'><span class='stepSpinner'></span></span></div>\" +"
        "    \"<div class='overlayStep' data-step='studios'><span class='stepLabel'>Studios</span><span class='stepIcon' aria-hidden='true'><span class='stepSpinner'></span></span></div>\" +"
        "    \"<div class='overlayStep' data-step='genres'><span class='stepLabel'>Genres</span><span class='stepIcon' aria-hidden='true'><span class='stepSpinner'></span></span></div>\" +"
        "  \"</div>\" +"
        "  \"<div class='overlayRule'></div>\" +"
        "  \"<div class='overlaySub'>Fetching new data from Jellyfin</div>\";"
        "}"
        "function setStepDone(stepKey){"
        " const row = overlayBox ? overlayBox.querySelector(`.overlayStep[data-step='${stepKey}']`) : null;"
        " if(!row) return;"
        " row.classList.add('done');"
        " const icon = row.querySelector('.stepIcon');"
        " if(icon) icon.innerHTML = \"<span class='stepCheck' aria-hidden='true'>✓</span>\";"
        "}"
        "function showOverlaySuccessAndReload(){"
        " if(!overlayBox) return;"
        " overlayBox.innerHTML = \"<div class='overlaySuccess' id='overlaySuccess' aria-hidden='true'>✓</div>\";"
        " const el = document.getElementById('overlaySuccess');"
        " const finish = ()=>{"
        "  const u = new URL(window.location.href);"
        "  u.searchParams.set('v', Date.now().toString());"
        "  window.location.href = u.toString();"
        " };"
        " if(el){"
        "  el.addEventListener('animationend', finish, { once:true });"
        "  setTimeout(finish, 900);"
        " } else {"
        "  setTimeout(finish, 700);"
        " }"
        "}"
        "if(refreshBtn){"
        " refreshBtn.addEventListener('click', ()=>{"
        "  if(window.location.protocol === 'file:'){"
        "    alert('Refresh requires a local server. Start the server and open the page via http://127.0.0.1:8787/');"
        "    return;"
        "  }"
        "  refreshBtn.disabled = true;"
        "  refreshBtn.classList.add('loading');"
        "  if(overlay){ overlay.classList.add('show'); overlay.setAttribute('aria-hidden','false'); }"
        "  document.body.classList.add('noScroll');"
        "  resetOverlaySteps();"
        "  const ref = encodeURIComponent(window.location.href);"
        "  const es = new EventSource('/refresh/stream?ref=' + ref);"
        "  const cleanup = ()=>{"
        "    try{ es.close(); }catch(e){}"
        "    refreshBtn.disabled = false;"
        "    refreshBtn.classList.remove('loading');"
        "  };"
        "  es.addEventListener('step', (ev)=>{"
        "    try{"
        "      const msg = JSON.parse(ev.data || '{}');"
        "      if(msg.step) setStepDone(msg.step);"
        "    }catch(e){}"
        "  });"
        "  es.addEventListener('done', ()=>{"
        "    cleanup();"
        "    setTimeout(()=>{ showOverlaySuccessAndReload(); }, 200);"
        "  });"
        "  es.addEventListener('error', ()=>{"
        "    cleanup();"
        "    if(overlay){ overlay.classList.remove('show'); overlay.setAttribute('aria-hidden','true'); }"
        "    document.body.classList.remove('noScroll');"
        "    alert('Could not refresh. Is the server running?');"
        "  });"
        " });"
        "}"
        "if(q) q.addEventListener('input', update);"
        "if(sortBy) sortBy.addEventListener('change', update);"
        "if(sortDirBtn) sortDirBtn.addEventListener('click', ()=>{"
        " sortDir = (sortDir==='asc') ? 'desc' : 'asc';"
        " sortDirBtn.textContent = (sortDir==='asc') ? '▲' : '▼';"
        " update();"
        "});"
        "azButtons.forEach(btn=>{"
        " btn.addEventListener('click', ()=>{"
        "  azButtons.forEach(b=>b.classList.remove('active'));"
        "  btn.classList.add('active');"
        "  activeLetter=btn.dataset.letter;"
        "  update();"
        " });"
        "});"
        "qaButtons.forEach(btn=>{"
        " btn.addEventListener('click', ()=>{"
        "  qaButtons.forEach(b=>b.classList.remove('active'));"
        "  btn.classList.add('active');"
        "  missingMode = btn.dataset.missing || 'ALL';"
        "  update();"
        " });"
        "});"
        "tagButtons.forEach(btn=>{"
        " btn.addEventListener('click', ()=>{"
        "  const t=btn.dataset.tag;"
        "  if(selectedTags.has(t)){"
        "    selectedTags.delete(t);"
        "    btn.classList.remove('active');"
        "  } else {"
        "    selectedTags.add(t);"
        "    btn.classList.add('active');"
        "  }"
        "  syncMiniBadges(t);"
        "  update();"
        " });"
        "});"
        "if(tagClear){"
        " tagClear.addEventListener('click', ()=>{"
        "  selectedTags=new Set();"
        "  tagButtons.forEach(b=>b.classList.remove('active'));"
        "  document.querySelectorAll('.tagMini').forEach(b=>b.classList.remove('active'));"
        "  update();"
        " });"
        "}"
        "document.addEventListener('click', (e)=>{"
        " const btn = e.target.closest('.tagMini');"
        " if(!btn) return;"
        " e.preventDefault();"
        " e.stopPropagation();"
        " const t = btn.dataset.tag;"
        " const chip = document.querySelector(`.tag[data-tag=\\\"${t}\\\"]`);"
        " if(selectedTags.has(t)){"
        "  selectedTags.delete(t);"
        "  btn.classList.remove('active');"
        "  if(chip) chip.classList.remove('active');"
        " } else {"
        "  selectedTags.add(t);"
        "  btn.classList.add('active');"
        "  if(chip) chip.classList.add('active');"
        " }"
        " syncMiniBadges(t);"
        " update();"
        "});"
        "update();"
        "</script>"
        "</body></html>",
        encoding="utf-8",
    )
